import { Node, Edge } from "../src/types/index";

export const sampleNodes: Node[] = [
  {
    id: "1",
    label: "Борба",
    type: "произведение",
    year: 1925,
    image: "",
    externalLink: "",
    description: "",
    tags: ["Революционна лирика", "Героическа поезия"],
  },
  {
    id: "Botev",
    label: "Христо Ботев",
    type: "автор",
    year: 1896,
    description: "",
    tags: [""],
  },
  {
    id: "4",
    label: "Депутатът с обърканите местоимения",
    type: "произведение",
    year: 1926,
    description:
      "герой–депутат, който говори в трето лице, символизира отчуждението на властта от народа. Езиковата грешка е метафора за изкривената реалност на политиците.",
    tags: ["Сатира"],
  },
  {
    id: "Aleko",
    label: "Алеко Константинов",
    type: "автор",
    year: 1899,
    description: "",
    tags: [],
  },
  {
    id: "6",
    label: "Политическа некомпетентност",
    type: "тема",
    year: 0,
    description: "",
  },
  {
    id: "Geo",
    label: "Гео Милев",
    type: "автор",
    year: 0,
    description: "",
    tags: [],
  },
  {
    id: "Dimo",
    label: "Димитър Димов",
    type: "автор",
    year: 0,
    description: "",
    tags: [],
  },
  {
    id: "Hristo",
    label: "Христо Смирненски",
    type: "автор",
    year: 1899,
    description: "",
    tags: [],
  },
  {
    id: "opression",
    label: "Насилствена власт",
    type: "тема",
    description: "",
    tags: [""],
  },
  {
    id: "10",
    label: "Tютюн",
    type: "произведение",
    year: 1926,
    description: "",
    tags: ["Социален роман"],
  },
  {
    id: "10",
    label: "Приказка за стълбата",
    type: "произведение",
    year: 1926,
    description: "",
    tags: ["Социален"],
  },
  {
    id: "11",
    label: "Андрешко",
    type: "произведение",
    year: 1926,
    description: " връзка с Елин пелин",
    tags: ["Социален роман"],
  },
  {
    id: "Lubo",
    label: "Любен Каравелов",
    type: "автор",
    year: 1899,
    description: "",
    tags: [],
  },
  {
    id: "13",
    label: "Крива ли е съдбата",
    type: "произведение",
    year: 1926,
    description: "",
    tags: ["Социален роман"],
  },
  {
    id: "Elin",
    label: "Елин Пелин",
    type: "автор",
    year: 1899,
    description: "",
    tags: [],
  },
  {
    id: "Vapcarov",
    label: "Никола Вапцаров",
    type: "автор",
    year: 1899,
    description: "",
    tags: [],
  },
  {
    id: "21",
    label: "Пловдив",
    type: "произведение",
    year: 1926,
    description: "",
    tags: [],
  },
  {
    id: "22",
    label: "Под игото",
    type: "произведение",
    year: 1926,
    description: "",
    tags: [],
  },
  {
    id: "23",
    label: "История",
    type: "произведение",
    year: 1926,
    description: "",
    tags: [],
  },
  {
    id: "24",
    label: "Истина за стълбата",
    type: "произведение",
    year: 1926,
    description: "",
    tags: [],
  },
  {
    id: "25",
    label: "На гости у Дявола",
    type: "произведение",
    year: 1926,
    description: "",
    tags: [],
  },
];

export const sampleEdges: Edge[] = [
  // { source: "1", target: "2", type: "автор на" },
  // { source: "1", target: "3", type: "тема" },
  // { source: "4", target: "5", type: "автор на" },
  // { source: "4", target: "3", type: "тема" },
  // { source: "6", target: "5", type: "автор на" },
  // { source: "7", target: "8", type: "автор на" },
  // { source: "7", target: "9", type: "тема" },
  // { source: "10", target: "11", type: "автор на" },
  // { source: "10", target: "12", type: "тема" },
  // { source: "5", target: "3", type: "повлиян" },
  // { source: "8", target: "9", type: "тема" },
  // { source: "11", target: "12", type: "повлиян" },
];
